# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, dev, devel]
  pull_request:
    branches: [main, master, dev, devel]

name: HTML5 check

jobs:
  HTML5-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'
          http-user-agent: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          dependencies: 'character()'

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install tidy and pandoc
        run: sudo apt install tidy pandoc
        
      - name: Install dependencies
        run: R -e 'install.packages(c("knitr", "rmarkdown", "XML", "httr", "data.table", "maps", "dplyr", "tidyr", "xml2", "testthat", "archive"))'
        
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--as-cran")'
          build_args: 'character()'
          error-on: '"note"'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          LANG: "en_US.UTF.8"
